version: '3.7'

services:
  cli:
    build:
      context: .
      dockerfile: dev.Dockerfile
    user: '1000'
    command: bash
    volumes:
      - ./:/app
      - ~/.gitconfig/:/root/.gitconfig
    working_dir: /app
