version: '3.7'

services:
  test:
    image: node:12-alpine
    user: '1000'
    command: yarn test
    environment:
      DB_TYPE: postgres
      DB_HOST: test_postgres
      DB_PORT: 5432
      DB_USERNAME: root
      DB_PASSWORD: test
      DB_DATABASE: financial-transactions
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - test_postgres

  test_postgres:
    image: paliari/postgres-postgis:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test
      POSTGRES_DB: financial-transactions
